### ISSUE TITLE
ML Base URI Template problem

### ISSUE THREAD

**Issue by MikeSQ** [toddkitta/AdventureWorksTravel#2]
I was running through the lab, and stumbled when trying to consume the ML web service. The application kept throwing an exception:
`"Prediction did not succeed. Check the Settings for mlWorkspaceId, mlServiceId, and mlApiKey."`

Each of the settings was correct (checked, checked, and triple checked) so I downloaded the repo and debugged locally to find that the call to the ML service was continuously throwing `401 unauthorized` errors.

The problem ended up being that the code is expecting the web service URI to be of this format:
`"https://{0}.services.azureml.net/subscriptions/{1}/services/{2}/execute?api-version=2.0&details=true";`

But the actual URI was of this format:
`"https://{0}.services.azureml.net/workspaces/{1}/services/{2}/execute?api-version=2.0&details=true";`

I'm not sure if this was a misstep for me somewhere along the line or not, others in the workshop did not have this issue. Either way, it might be worthwhile to consider changing the `/subscriptions/` to be parameterized as well? Or maybe changing the template creation to just ask for the Request-Response URL directly and parse out the portions you need elsewhere?

edit: Just noticed that the URI actually used to be `/workspaces/` until [commit 827e970](https://github.com/toddkitta/AdventureWorksTravel/commit/827e9707083bcba947cdd8ac78e742d9cfb23d00). Is it possible I received the old URI because I had signed up with a machine learning account prior to today?

**Comment by toddkitta** [comment]
@MikeSQ First, sorry I'm just now seeing this. Can you please confirm that you are using the workspace that was provisioned as part of the workshop deployment script (http://aka.ms/cortanasetup)? My guess is you are using a different workspace that has been around for a while (the older ones have different behavior).

**Comment by MikeSQ** [comment]
Yes, I followed the provisioning script exactly. I was the only person in the class with the issue, I'm pretty sure I had accessed the ML stuff once when it was first released, my guess is that somehow locked in my REST URI, but not sure.

**Comment by toddkitta** [comment]
If you have another ML workspace provisioned, it can be very easy to confuse the two workspaces. You can tell which one you are in by looking at the workspace selector at the top right of your screen. My guess is that when you went to ML studio, it defaulted to the previously created ML workspace even though the new one was provisioned as part of the workshop.
